### PR TITLE
Chore: upgrade docusaurus and plugins version to 2.0.0-beta.14

### PR DESCRIPTION
**Pull request by khushal87**
This PR upgrades the docusaurus and its related plugin versions from 2.0.0-beta.5 to 2.0.0-beta.14.

Notable changes can be referred from: https://github.com/facebook/docusaurus/releases

The `themeConfig.metadatas` is changed to `themeConfig.metadata` in the new versions and therefore I have updated here in the configs.

### CODE REVIEW

**Comment by petyosi** [comment]
Question - previously upgrading through betas was quite painful - did you test all SDK docs with it (in Dev and combined?)?

**Comment by khushal87** [comment]
@petyosi Just tested across all the SDKs:
- Android
- iOS/Swift
- React
- React Native
- Flutter
Things look fine for all of them no major breakdown or UI issue as such. 
image
Reference for all the SDK docs working 😄

**Review by petyosi — APPROVED** [review]
Just ensure that merge it into staging first.

**Comment by khushal87** [comment]
@petyosi Can you give it a test/review? Since I didn't get time after the last review and new versions are added with bug fixes and improvement hence I have upgraded it to `2.0.0-beta.14` as per the latest standards. 

PS: I have tested on my side on all of the SDKs and they seem to work fine :)

**Comment by madsroskar** [comment]
That 9765a50, 3f16be1 and 3342d10 makes it look like me and Vish haven't merged those commits into staging, I want to sort that out before this is merged

**Comment by khushal87** [comment]
The ideal workflow for merges is `your branch` -> `staging` -> `production` as per the conversation I had with Petyo.

**Comment by madsroskar** [comment]
You're right, I believe we just forgot or didn't think about it while trying to get our versioned docs working a few weeks back. Our mistake, but I'm fixing it. Mentioned it here since it's how I realized it. :)

**Pull request merged**
