### PR TITLE
Remove the tar.gz

### PR DESCRIPTION
**Pull request by petyosi**
The change flattens the project structure, and removes the concept of "installation". This removed the plugins feature, which was not used. 

It also does some minor changes around the algolia indexing, so that we can simplify how `stream-chat-docusaurus` workflow does it.

Please test with your repos - I did but I am not sure if the warnings are due to that or something else.

### CODE REVIEW

**Comment by petyosi** [comment]
PR review instructions:
- Don't look at the changes, except for the [README.md one](https://github.com/GetStream/stream-chat-docusaurus-cli/pull/59/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5). 
- Checkout the branch locally, remove any symlinks from the previous setup. 
- do what you usually do with docs - see if there are any warnings that should not be there or something does not build.

**Comment by petyosi** [comment]
Blocked by a ReviewNote component in stream-chat-react that picks multiple react versions. Solvable by making the said component non-interactive.

**Review by szuperaz — APPROVED** [review]
Works with `stream-chat-angular` and `stream-video-js`

**Review by khushal87 — APPROVED** [review]
Tested:
- React Native Chat
- Flutter Chat
- Swift Chat

Green Signal from all ✅

**Comment by khushal87** [comment]
Just a small thing to check:

Running `yarn start`, `yarn build`, `yarn swizzle` in the repo throws:
```
[ERROR] TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:372:5)
    at validateString (node:internal/validators:120:11)
    at Object.join (node:path:1172:7)
    at Object.<anonymous> (/Users/khushalagarwal/Stream/stream-chat-docusaurus-cli/docusaurus.config.js:6:41)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at module.exports (/Users/khushalagarwal/Stream/stream-chat-docusaurus-cli/node_modules/import-fresh/index.js:32:59)
    at loadConfig (/Users/khushalagarwal/Stream/stream-chat-docusaurus-cli/node_modules/@docusaurus/core/lib/server/config.js:17:53)
    at loadSiteConfig (/Users/khushalagarwal/Stream/stream-chat-docusaurus-cli/node_modules/@docusaurus/core/lib/server/index.js:34:51)
    at loadContext (/Users/khushalagarwal/Stream/stream-chat-docusaurus-cli/node_modules/@docusaurus/core/lib/server/index.js:44:69)
    at load (/Users/khushalagarwal/Stream/stream-chat-docusaurus-cli/node_modules/@docusaurus/core/lib/server/index.js:203:27)
    at loadSite (/Users/khushalagarwal/Stream/stream-chat-docusaurus-cli/node_modules/@docusaurus/core/lib/commands/start.js:32:34)
    at start (/Users/khushalagarwal/Stream/stream-chat-docusaurus-cli/node_modules/@docusaurus/core/lib/commands/start.js:39:25)
error Command failed with exit code 1.
```

**Comment by petyosi** [comment]
@khushal87 running those commands in the repo itself does not make sense. They should be executed in the context of a content repo, where the path is correctly set.

**Pull request merged**
